### PR TITLE
putting kubernetes config as list

### PR DESCRIPTION
**Pull request by GuilhermeCamposo**

### CODE REVIEW

**Comment by davivcgarcia** [comment]
@GuilhermeCamposo have you tested this new syntax on a OCP 4.3? Looks like the UI doesn't recognize List as a valid resource type. I'll revert the change for now, since the original format is valid if used with `oc apply`.

Screenshot from 2020-03-21 22-33-26

**Comment by GuilhermeCamposo** [comment]
I guess we just found a bug in the console. The list object is present in k8s for a long time  and it’s used when you retrieve a list of object. I tested in 4.3.5  using “oc create” and it worked. I will definitely file a bug for this.

**Comment by davivcgarcia** [comment]
This is the same behavior with the other file format, without the `type List`. I think this is a limitation of the OpenShift UI, not exactly a bug.

**Comment by GuilhermeCamposo** [comment]
We should get a warning or something similar. Not a error message saying it is not a recognizable resource. It is also a regression issue, because it was possible to create this kind of object in the 3.11 console.

**Pull request merged**
